// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1;

namespace Parcial1.Migrations
{
    [DbContext(typeof(TareasDB))]
    [Migration("20201008222933_recursos")]
    partial class recursos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Parcial1.Recurso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("Parcial1.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("clave")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.Property<string>("usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Parcial1.Recurso", b =>
                {
                    b.HasOne("Parcial1.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });
#pragma warning restore 612, 618
        }
    }
}
