// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parcial1;

namespace Parcial1.Migrations
{
    [DbContext(typeof(TareasDB))]
    [Migration("20201009211401_resu")]
    partial class resu
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Parcial1.Detalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Recursoid")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Tareaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("tiempo")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("Recursoid");

                    b.HasIndex("Tareaid");

                    b.ToTable("Detalle");
                });

            modelBuilder.Entity("Parcial1.Recurso", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.Property<int?>("usuarioid")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("usuarioid");

                    b.ToTable("Recurso");
                });

            modelBuilder.Entity("Parcial1.Tarea", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("estimacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("responsableid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("titulo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("vencimiento")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("responsableid");

                    b.ToTable("Tarea");
                });

            modelBuilder.Entity("Parcial1.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("clave")
                        .HasColumnType("INTEGER")
                        .HasMaxLength(50);

                    b.Property<string>("usuario")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Parcial1.Detalle", b =>
                {
                    b.HasOne("Parcial1.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("Recursoid");

                    b.HasOne("Parcial1.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("Tareaid");
                });

            modelBuilder.Entity("Parcial1.Recurso", b =>
                {
                    b.HasOne("Parcial1.Usuario", "usuario")
                        .WithMany()
                        .HasForeignKey("usuarioid");
                });

            modelBuilder.Entity("Parcial1.Tarea", b =>
                {
                    b.HasOne("Parcial1.Recurso", "responsable")
                        .WithMany()
                        .HasForeignKey("responsableid");
                });
#pragma warning restore 612, 618
        }
    }
}
